### ISSUE TITLE
BUG Game Crashes Blood Magic

### ISSUE THREAD

**Issue by K3ll06s** [Darkosto/SevTech-Ages#1557]
2 Game Crashes with Blood Magic

GameCrash: permanent crash on load
I crafted the sigil of the green growth and wanted to use it.
I put it in the sigil of holding and wanted to actiavte it and my game crashed.
If i try to reload the game crashes again.

Steps to Reproduce (for bugs)
As trying to reproduce the green growth crash in a new world i got the same crash with the blood lamp as yesterday.
1. Build blood altar
2. Use orb to fill network
3. Use sigil of green growth, works fine
4. Use Sigil of the blood lamp game crash, client.txt
5. Restart game, load world, error and back to main menu, no crash report
6. Reload of the world seems fine, blood lamp usable, sigil of the green growth as well, also usable in sigil of holding
Can't reproduce the bug with the green growth sigil.

Client Information
* Modpack Version: 3.0.5
* Java Version: 1.8.0_161, Oracle Corporation
* Launcher Used: Twitch launcher, jav version
* Resourcepack Enabled?: Soartex, Soartex Modded
* Optifine Installed?: yes and no

crashlogs after 4.07_15.05 without optifine, the older ones have optifine enabled
[crash-2018-04-07_14.41.17-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1886383/crash-2018-04-07_14.41.17-server.txt)
[crash-2018-04-07_15.05.48-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1886384/crash-2018-04-07_15.05.48-server.txt)
[crash-2018-04-07_14.58.31-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1886385/crash-2018-04-07_14.58.31-server.txt)

Had a gamecrash yesterday as i started to use the blood lamp, but no further problems after a restart. ModPack version 3.0.4
[crash-2018-04-06_18.57.03-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1886386/crash-2018-04-06_18.57.03-client.txt)

BloodLamp recreating crash
[crash-2018-04-07_15.27.09-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1886394/crash-2018-04-07_15.27.09-client.txt)

**Comment by TehNut** [comment]
Blood Lamp crash was fixed by https://github.com/WayofTime/BloodMagic/commit/08031e65f822e877427e7e7084a29b94011391de and the holding sigil crash was fixed by https://github.com/WayofTime/BloodMagic/commit/03a2904bd15a60603dde51aeb6f953fd7d68f49a. They'll be in the next build whenever I get around to pushing it.

**Comment by lslinnet** [comment]
@TehNut Would it break anything to update Blood magic manually, would like to continue my game and is currently stuck due to this bug.

**Comment by TehNut** [comment]
I'unno. Blood Magic isn't exactly stable right now. It's marked as an alpha for a reason. You can try I guess.

**Comment by Ogini** [comment]
I've had the same issue - with neither of MCEdit, deleting player..dat file working. However, after "unlocking" the pack and updating Blood Magic, I was able to log in again. So I can confirm the update fixes the issue.

**Comment by Veskandar** [comment]
2.2.11-96 update of blood magic does not fix the sigil of magnatism crash

**Comment by justinrusso** [comment]
@Veskandar submit an issue on the blood magic tracker if there is not one already.

**Comment by Veskandar** [comment]
@justinrusso has been done
